name: CD

on:
  push:
    branches:
      - master
    tags:
      - "!*"
    paths-ignore:
      - "docs/**/*"
      - "README.md"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: npm run format
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          npm install
          npm run format:check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: npm run lint
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          npm install
          npm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: npm run typecheck
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          npm install
          npm run typecheck

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: npm test
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          npm install
          npm test

  publish:
    needs: [format, lint, typecheck, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Check version changes
        uses: EndBug/version-check@v1
        id: check
        with:
          diff-search: true
          file-name: package.json
      - name: npm publish --access public
        if: steps.check.outputs.changed == 'true'
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          npm install
          npm publish --access public

      - name: npm publish --dry-run --access public
        if: steps.check.outputs.changed != 'true'
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          npm install
          npm publish --dry-run --access public
