name: CI

on: push

jobs:
  Audit:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: npm audit
      run: |
        npm install
        npm audit
        
  Format:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: npm run format
      run: |
        npm install
        npm run format:check
        
  Lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: npm run lint
      run: |
        npm install
        npm run lint
        
  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: npm test
      run: |
        npm install
        npm test
        
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: npm run build
      run: |
        npm install
        npm run build
